### ISSUE TITLE
[Feature Request] Folia support

### ISSUE THREAD

**Issue by BigPebble123** [M64DiamondStar/EffectMaster#1]
Can you please add Folia support?

All that you need to do is replace the `Bukkit.getScheduler` calls with `UniversalScheduler`:
https://github.com/Anon8281/UniversalScheduler

Also add `folia-supported: true` to `plugin.yml`.

**Comment by Ym64** [comment]
I'll see if I can add that. Sorry for not responding that quickly, don't use github issues that often haha

**Comment by Ym64** [comment]
Hey sorry for the late response but I’ve successfully replaced all the schedule methods with ones that support folia. I don’t have the hardware to test it but it should work right now!
